# Generated by Django 3.2.5 on 2021-07-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='licence_categories',
            new_name='categories',
        ),
    ]
