# Generated by Django 3.2.5 on 2021-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_vehiclebreakdown_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
