# Generated by Django 3.2.5 on 2021-07-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_accident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accident',
        ),
    ]
