# Generated by Django 3.2.5 on 2021-07-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20210727_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_registration',
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_started', models.DateField()),
                ('insurance_expires', models.DateField()),
                ('insurance_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_polices', to='vehicle.insurancecompany')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='vehicle.vehicle')),
            ],
        ),
    ]
