# Generated by Django 3.2.5 on 2021-07-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20210729_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'verbose_name_plural': 'Insurance companies'},
        ),
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'verbose_name_plural': 'Insurance policies'},
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='policy_code',
            field=models.CharField(default='21 301', max_length=50),
            preserve_default=False,
        ),
    ]
