# Generated by Django 3.2.5 on 2021-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20210729_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, default='PGDZ294', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
