# Generated by Django 3.2.5 on 2021-08-08 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20210801_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{9,10}$')]),
        ),
    ]
